[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("432F7A9F-E887-4F14-876F-6E3BCF4BCE2E")]
[assembly: System.Reflection.AssemblyVersion("6.0.0.0")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("RazorRockstars.Web.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("ServiceStack.WebHost.Endpoints.Tests")]
