// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AutorestClient
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for HelloAllTypesOperations.
    /// </summary>
    public static partial class HelloAllTypesOperationsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='allTypes'>
            /// </param>
            /// <param name='allCollectionTypes'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static object Get(this IHelloAllTypesOperations operations, string name = default(string), object allTypes = default(object), object allCollectionTypes = default(object), string format = "json")
            {
                return operations.GetAsync(name, allTypes, allCollectionTypes, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='allTypes'>
            /// </param>
            /// <param name='allCollectionTypes'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAsync(this IHelloAllTypesOperations operations, string name = default(string), object allTypes = default(object), object allCollectionTypes = default(object), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(name, allTypes, allCollectionTypes, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='allTypes'>
            /// </param>
            /// <param name='allCollectionTypes'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static object Create(this IHelloAllTypesOperations operations, string name = default(string), object allTypes = default(object), object allCollectionTypes = default(object), HelloAllTypes body = default(HelloAllTypes), string format = "json")
            {
                return operations.CreateAsync(name, allTypes, allCollectionTypes, body, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='allTypes'>
            /// </param>
            /// <param name='allCollectionTypes'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> CreateAsync(this IHelloAllTypesOperations operations, string name = default(string), object allTypes = default(object), object allCollectionTypes = default(object), HelloAllTypes body = default(HelloAllTypes), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateWithHttpMessagesAsync(name, allTypes, allCollectionTypes, body, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='allTypes'>
            /// </param>
            /// <param name='allCollectionTypes'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static object Post(this IHelloAllTypesOperations operations, string name = default(string), object allTypes = default(object), object allCollectionTypes = default(object), HelloAllTypes body = default(HelloAllTypes), string format = "json")
            {
                return operations.PostAsync(name, allTypes, allCollectionTypes, body, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='allTypes'>
            /// </param>
            /// <param name='allCollectionTypes'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PostAsync(this IHelloAllTypesOperations operations, string name = default(string), object allTypes = default(object), object allCollectionTypes = default(object), HelloAllTypes body = default(HelloAllTypes), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostWithHttpMessagesAsync(name, allTypes, allCollectionTypes, body, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='allTypes'>
            /// </param>
            /// <param name='allCollectionTypes'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static object Delete(this IHelloAllTypesOperations operations, string name = default(string), object allTypes = default(object), object allCollectionTypes = default(object), string format = "json")
            {
                return operations.DeleteAsync(name, allTypes, allCollectionTypes, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='allTypes'>
            /// </param>
            /// <param name='allCollectionTypes'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> DeleteAsync(this IHelloAllTypesOperations operations, string name = default(string), object allTypes = default(object), object allCollectionTypes = default(object), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeleteWithHttpMessagesAsync(name, allTypes, allCollectionTypes, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
