// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AutorestClient
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for HelloZipOperations.
    /// </summary>
    public static partial class HelloZipOperationsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static HelloZipResponse Get(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json")
            {
                return operations.GetAsync(name, test, body, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<HelloZipResponse> GetAsync(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(name, test, body, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static HelloZipResponse Create(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json")
            {
                return operations.CreateAsync(name, test, body, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<HelloZipResponse> CreateAsync(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateWithHttpMessagesAsync(name, test, body, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static HelloZipResponse Post(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json")
            {
                return operations.PostAsync(name, test, body, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<HelloZipResponse> PostAsync(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostWithHttpMessagesAsync(name, test, body, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static HelloZipResponse Delete(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json")
            {
                return operations.DeleteAsync(name, test, body, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<HelloZipResponse> DeleteAsync(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeleteWithHttpMessagesAsync(name, test, body, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static HelloZipResponse Update(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json")
            {
                return operations.UpdateAsync(name, test, body, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='test'>
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<HelloZipResponse> UpdateAsync(this IHelloZipOperations operations, string name = default(string), IList<string> test = default(IList<string>), HelloZip body = default(HelloZip), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.UpdateWithHttpMessagesAsync(name, test, body, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
