//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStack.Examples.Clients.ExamplesSoapEndpoint {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.servicestack.net/types")]
    [System.SerializableAttribute()]
    public partial class ResponseStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseError[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseError[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.servicestack.net/types")]
    [System.SerializableAttribute()]
    public partial class ResponseError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://schemas.servicestack.net/types", ItemName="Long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.servicestack.net/types")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GlobalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GlobalId {
            get {
                return this.GlobalIdField;
            }
            set {
                if ((this.GlobalIdField.Equals(value) != true)) {
                    this.GlobalIdField = value;
                    this.RaisePropertyChanged("GlobalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerOrders", Namespace="http://schemas.servicestack.net/types")]
    [System.SerializableAttribute()]
    public partial class CustomerOrders : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Order[] OrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.servicestack.net/types")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactTitle {
            get {
                return this.ContactTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactTitleField, value) != true)) {
                    this.ContactTitleField = value;
                    this.RaisePropertyChanged("ContactTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.servicestack.net/types")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceStack.Examples.Clients.ExamplesSoapEndpoint.OrderDetail[] OrderDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceStack.Examples.Clients.ExamplesSoapEndpoint.OrderHeader OrderHeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.OrderDetail[] OrderDetails {
            get {
                return this.OrderDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDetailsField, value) != true)) {
                    this.OrderDetailsField = value;
                    this.RaisePropertyChanged("OrderDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.OrderHeader OrderHeader {
            get {
                return this.OrderHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderHeaderField, value) != true)) {
                    this.OrderHeaderField = value;
                    this.RaisePropertyChanged("OrderHeader");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderHeader", Namespace="http://schemas.servicestack.net/types")]
    [System.SerializableAttribute()]
    public partial class OrderHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FreightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RequiredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShipViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ShippedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Freight {
            get {
                return this.FreightField;
            }
            set {
                if ((this.FreightField.Equals(value) != true)) {
                    this.FreightField = value;
                    this.RaisePropertyChanged("Freight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RequiredDate {
            get {
                return this.RequiredDateField;
            }
            set {
                if ((this.RequiredDateField.Equals(value) != true)) {
                    this.RequiredDateField = value;
                    this.RaisePropertyChanged("RequiredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipAddress {
            get {
                return this.ShipAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipAddressField, value) != true)) {
                    this.ShipAddressField = value;
                    this.RaisePropertyChanged("ShipAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipCity {
            get {
                return this.ShipCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipCityField, value) != true)) {
                    this.ShipCityField = value;
                    this.RaisePropertyChanged("ShipCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipCountry {
            get {
                return this.ShipCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipCountryField, value) != true)) {
                    this.ShipCountryField = value;
                    this.RaisePropertyChanged("ShipCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipName {
            get {
                return this.ShipNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipNameField, value) != true)) {
                    this.ShipNameField = value;
                    this.RaisePropertyChanged("ShipName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipPostalCode {
            get {
                return this.ShipPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipPostalCodeField, value) != true)) {
                    this.ShipPostalCodeField = value;
                    this.RaisePropertyChanged("ShipPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipRegion {
            get {
                return this.ShipRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipRegionField, value) != true)) {
                    this.ShipRegionField = value;
                    this.RaisePropertyChanged("ShipRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShipVia {
            get {
                return this.ShipViaField;
            }
            set {
                if ((this.ShipViaField.Equals(value) != true)) {
                    this.ShipViaField = value;
                    this.RaisePropertyChanged("ShipVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShippedDate {
            get {
                return this.ShippedDateField;
            }
            set {
                if ((this.ShippedDateField.Equals(value) != true)) {
                    this.ShippedDateField = value;
                    this.RaisePropertyChanged("ShippedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetail", Namespace="http://schemas.servicestack.net/types")]
    [System.SerializableAttribute()]
    public partial class OrderDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.servicestack.net/types")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GenresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Director {
            get {
                return this.DirectorField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorField, value) != true)) {
                    this.DirectorField = value;
                    this.RaisePropertyChanged("Director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Genres {
            get {
                return this.GenresField;
            }
            set {
                if ((object.ReferenceEquals(this.GenresField, value) != true)) {
                    this.GenresField = value;
                    this.RaisePropertyChanged("Genres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagLine {
            get {
                return this.TagLineField;
            }
            set {
                if ((object.ReferenceEquals(this.TagLineField, value) != true)) {
                    this.TagLineField = value;
                    this.RaisePropertyChanged("TagLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.servicestack.net/", ConfigurationName="ExamplesSoapEndpoint.ISyncReply")]
    public interface ISyncReply {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message GreetRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/Greet", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GreetResponse Greet(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GreetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message GetFactorialRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/GetFactorial", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFactorialResponse GetFactorial(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFactorialRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message StoreNewUserRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/StoreNewUser", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.StoreNewUserResponse StoreNewUser(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.StoreNewUserRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message GetFibonacciNumbersRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/GetFibonacciNumbers", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFibonacciNumbersResponse GetFibonacciNumbers(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFibonacciNumbersRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message ResetMovieDatabaseRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/ResetMovieDatabase", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResetMovieDatabaseResponse ResetMovieDatabase(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResetMovieDatabaseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message DeleteAllUsersRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/DeleteAllUsers", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.DeleteAllUsersResponse DeleteAllUsers(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.DeleteAllUsersRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message GetAllUsersRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/GetAllUsers", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetAllUsersResponse GetAllUsers(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message GetNorthwindCustomerOrdersRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/GetNorthwindCustomerOrders", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersResponse GetNorthwindCustomerOrders(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message GetUsersRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/GetUsers", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetUsersResponse GetUsers(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message GetNorthwindCustomerOrdersCachedRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/GetNorthwindCustomerOrdersCached", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersCachedResponse GetNorthwindCustomerOrdersCached(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersCachedRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.servicestack.net/types) of message MoviesRequest does not match the default value (http://services.servicestack.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.servicestack.net/Movies", ReplyAction="*")]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.MoviesResponse Movies(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.MoviesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Greet", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GreetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public string Name;
        
        public GreetRequest() {
        }
        
        public GreetRequest(string Name) {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GreetResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GreetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public string Result;
        
        public GreetResponse() {
        }
        
        public GreetResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFactorial", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetFactorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public long ForNumber;
        
        public GetFactorialRequest() {
        }
        
        public GetFactorialRequest(long ForNumber) {
            this.ForNumber = ForNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFactorialResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetFactorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public long Result;
        
        public GetFactorialResponse() {
        }
        
        public GetFactorialResponse(long Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StoreNewUser", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class StoreNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=2)]
        public string UserName;
        
        public StoreNewUserRequest() {
        }
        
        public StoreNewUserRequest(string Email, string Password, string UserName) {
            this.Email = Email;
            this.Password = Password;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StoreNewUserResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class StoreNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public long UserId;
        
        public StoreNewUserResponse() {
        }
        
        public StoreNewUserResponse(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus, long UserId) {
            this.ResponseStatus = ResponseStatus;
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFibonacciNumbers", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetFibonacciNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public System.Nullable<long> Skip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public System.Nullable<long> Take;
        
        public GetFibonacciNumbersRequest() {
        }
        
        public GetFibonacciNumbersRequest(System.Nullable<long> Skip, System.Nullable<long> Take) {
            this.Skip = Skip;
            this.Take = Take;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFibonacciNumbersResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetFibonacciNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ArrayOfLong Results;
        
        public GetFibonacciNumbersResponse() {
        }
        
        public GetFibonacciNumbersResponse(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ArrayOfLong Results) {
            this.Results = Results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetMovieDatabase", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class ResetMovieDatabaseRequest {
        
        public ResetMovieDatabaseRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetMovieDatabaseResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class ResetMovieDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus;
        
        public ResetMovieDatabaseResponse() {
        }
        
        public ResetMovieDatabaseResponse(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus) {
            this.ResponseStatus = ResponseStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAllUsers", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class DeleteAllUsersRequest {
        
        public DeleteAllUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAllUsersResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class DeleteAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public long UserId;
        
        public DeleteAllUsersResponse() {
        }
        
        public DeleteAllUsersResponse(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus, long UserId) {
            this.ResponseStatus = ResponseStatus;
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllUsers", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetAllUsersRequest {
        
        public GetAllUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllUsersResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.User[] Users;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.User[] Users) {
            this.ResponseStatus = ResponseStatus;
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNorthwindCustomerOrders", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetNorthwindCustomerOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public string CustomerId;
        
        public GetNorthwindCustomerOrdersRequest() {
        }
        
        public GetNorthwindCustomerOrdersRequest(string CustomerId) {
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNorthwindCustomerOrdersResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetNorthwindCustomerOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.CustomerOrders CustomerOrders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus;
        
        public GetNorthwindCustomerOrdersResponse() {
        }
        
        public GetNorthwindCustomerOrdersResponse(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.CustomerOrders CustomerOrders, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus) {
            this.CustomerOrders = CustomerOrders;
            this.ResponseStatus = ResponseStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsers", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public long[] UserIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public string[] UserNames;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(long[] UserIds, string[] UserNames) {
            this.UserIds = UserIds;
            this.UserNames = UserNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.User[] Users;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.User[] Users) {
            this.ResponseStatus = ResponseStatus;
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNorthwindCustomerOrdersCached", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetNorthwindCustomerOrdersCachedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public string CustomerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public bool RefreshCache;
        
        public GetNorthwindCustomerOrdersCachedRequest() {
        }
        
        public GetNorthwindCustomerOrdersCachedRequest(string CustomerId, bool RefreshCache) {
            this.CustomerId = CustomerId;
            this.RefreshCache = RefreshCache;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNorthwindCustomerOrdersCachedResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class GetNorthwindCustomerOrdersCachedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public System.DateTime CreatedDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.CustomerOrders CustomerOrders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=2)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus;
        
        public GetNorthwindCustomerOrdersCachedResponse() {
        }
        
        public GetNorthwindCustomerOrdersCachedResponse(System.DateTime CreatedDate, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.CustomerOrders CustomerOrders, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus) {
            this.CreatedDate = CreatedDate;
            this.CustomerOrders = CustomerOrders;
            this.ResponseStatus = ResponseStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Movies", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class MoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public string Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Movie Movie;
        
        public MoviesRequest() {
        }
        
        public MoviesRequest(string Id, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Movie Movie) {
            this.Id = Id;
            this.Movie = Movie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoviesResponse", WrapperNamespace="http://schemas.servicestack.net/types", IsWrapped=true)]
    public partial class MoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=0)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Movie[] Movies;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.servicestack.net/types", Order=1)]
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus;
        
        public MoviesResponse() {
        }
        
        public MoviesResponse(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Movie[] Movies, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus) {
            this.Movies = Movies;
            this.ResponseStatus = ResponseStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISyncReplyChannel : ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SyncReplyClient : System.ServiceModel.ClientBase<ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply>, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply {
        
        public SyncReplyClient() {
        }
        
        public SyncReplyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncReplyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncReplyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncReplyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GreetResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.Greet(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GreetRequest request) {
            return base.Channel.Greet(request);
        }
        
        public string Greet(string Name) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GreetRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GreetRequest();
            inValue.Name = Name;
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GreetResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).Greet(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFactorialResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.GetFactorial(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFactorialRequest request) {
            return base.Channel.GetFactorial(request);
        }
        
        public long GetFactorial(long ForNumber) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFactorialRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFactorialRequest();
            inValue.ForNumber = ForNumber;
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFactorialResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).GetFactorial(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.StoreNewUserResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.StoreNewUser(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.StoreNewUserRequest request) {
            return base.Channel.StoreNewUser(request);
        }
        
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus StoreNewUser(string Email, string Password, string UserName, out long UserId) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.StoreNewUserRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.StoreNewUserRequest();
            inValue.Email = Email;
            inValue.Password = Password;
            inValue.UserName = UserName;
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.StoreNewUserResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).StoreNewUser(inValue);
            UserId = retVal.UserId;
            return retVal.ResponseStatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFibonacciNumbersResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.GetFibonacciNumbers(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFibonacciNumbersRequest request) {
            return base.Channel.GetFibonacciNumbers(request);
        }
        
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ArrayOfLong GetFibonacciNumbers(System.Nullable<long> Skip, System.Nullable<long> Take) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFibonacciNumbersRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFibonacciNumbersRequest();
            inValue.Skip = Skip;
            inValue.Take = Take;
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetFibonacciNumbersResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).GetFibonacciNumbers(inValue);
            return retVal.Results;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResetMovieDatabaseResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.ResetMovieDatabase(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResetMovieDatabaseRequest request) {
            return base.Channel.ResetMovieDatabase(request);
        }
        
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResetMovieDatabase() {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResetMovieDatabaseRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResetMovieDatabaseRequest();
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResetMovieDatabaseResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).ResetMovieDatabase(inValue);
            return retVal.ResponseStatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.DeleteAllUsersResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.DeleteAllUsers(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.DeleteAllUsersRequest request) {
            return base.Channel.DeleteAllUsers(request);
        }
        
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus DeleteAllUsers(out long UserId) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.DeleteAllUsersRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.DeleteAllUsersRequest();
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.DeleteAllUsersResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).DeleteAllUsers(inValue);
            UserId = retVal.UserId;
            return retVal.ResponseStatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetAllUsersResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.GetAllUsers(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus GetAllUsers(out ServiceStack.Examples.Clients.ExamplesSoapEndpoint.User[] Users) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetAllUsersRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetAllUsersRequest();
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetAllUsersResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).GetAllUsers(inValue);
            Users = retVal.Users;
            return retVal.ResponseStatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.GetNorthwindCustomerOrders(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersRequest request) {
            return base.Channel.GetNorthwindCustomerOrders(request);
        }
        
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.CustomerOrders GetNorthwindCustomerOrders(string CustomerId, out ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersRequest();
            inValue.CustomerId = CustomerId;
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).GetNorthwindCustomerOrders(inValue);
            ResponseStatus = retVal.ResponseStatus;
            return retVal.CustomerOrders;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetUsersResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.GetUsers(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus GetUsers(long[] UserIds, string[] UserNames, out ServiceStack.Examples.Clients.ExamplesSoapEndpoint.User[] Users) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetUsersRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetUsersRequest();
            inValue.UserIds = UserIds;
            inValue.UserNames = UserNames;
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetUsersResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).GetUsers(inValue);
            Users = retVal.Users;
            return retVal.ResponseStatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersCachedResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.GetNorthwindCustomerOrdersCached(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersCachedRequest request) {
            return base.Channel.GetNorthwindCustomerOrdersCached(request);
        }
        
        public System.DateTime GetNorthwindCustomerOrdersCached(string CustomerId, bool RefreshCache, out ServiceStack.Examples.Clients.ExamplesSoapEndpoint.CustomerOrders CustomerOrders, out ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersCachedRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersCachedRequest();
            inValue.CustomerId = CustomerId;
            inValue.RefreshCache = RefreshCache;
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.GetNorthwindCustomerOrdersCachedResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).GetNorthwindCustomerOrdersCached(inValue);
            CustomerOrders = retVal.CustomerOrders;
            ResponseStatus = retVal.ResponseStatus;
            return retVal.CreatedDate;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceStack.Examples.Clients.ExamplesSoapEndpoint.MoviesResponse ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply.Movies(ServiceStack.Examples.Clients.ExamplesSoapEndpoint.MoviesRequest request) {
            return base.Channel.Movies(request);
        }
        
        public ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Movie[] Movies(string Id, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.Movie Movie, out ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ResponseStatus ResponseStatus) {
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.MoviesRequest inValue = new ServiceStack.Examples.Clients.ExamplesSoapEndpoint.MoviesRequest();
            inValue.Id = Id;
            inValue.Movie = Movie;
            ServiceStack.Examples.Clients.ExamplesSoapEndpoint.MoviesResponse retVal = ((ServiceStack.Examples.Clients.ExamplesSoapEndpoint.ISyncReply)(this)).Movies(inValue);
            ResponseStatus = retVal.ResponseStatus;
            return retVal.Movies;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.servicestack.net/", ConfigurationName="ExamplesSoapEndpoint.IOneWay")]
    public interface IOneWay {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IOneWayChannel : ServiceStack.Examples.Clients.ExamplesSoapEndpoint.IOneWay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OneWayClient : System.ServiceModel.ClientBase<ServiceStack.Examples.Clients.ExamplesSoapEndpoint.IOneWay>, ServiceStack.Examples.Clients.ExamplesSoapEndpoint.IOneWay {
        
        public OneWayClient() {
        }
        
        public OneWayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OneWayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OneWayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OneWayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
}
