SET NUGET=..\src\.nuget\nuget
%NUGET% push ServiceStack.3.9.60.nupkg
%NUGET% push ServiceStack.3.9.60.symbols.nupkg
%NUGET% push ServiceStack.Api.Swagger.3.9.60.nupkg
%NUGET% push ServiceStack.Api.Swagger.3.9.60.symbols.nupkg
%NUGET% push ServiceStack.Authentication.OAuth2.3.9.60.nupkg
%NUGET% push ServiceStack.Authentication.OAuth2.3.9.60.symbols.nupkg
%NUGET% push ServiceStack.Authentication.OpenId.3.9.60.nupkg
%NUGET% push ServiceStack.Authentication.OpenId.3.9.60.symbols.nupkg
%NUGET% push ServiceStack.Client.Silverlight.3.9.60.nupkg
%NUGET% push ServiceStack.Common.3.9.60.nupkg
%NUGET% push ServiceStack.Common.3.9.60.symbols.nupkg
%NUGET% push ServiceStack.Host.AspNet.3.9.60.nupkg
%NUGET% push ServiceStack.Host.Mvc.3.9.60.nupkg
%NUGET% push ServiceStack.Mvc.3.9.60.nupkg
%NUGET% push ServiceStack.Mvc.3.9.60.symbols.nupkg
%NUGET% push ServiceStack.Plugins.MsgPack.3.9.60.nupkg
%NUGET% push ServiceStack.Plugins.MsgPack.3.9.60.symbols.nupkg
%NUGET% push ServiceStack.Plugins.ProtoBuf.3.9.60.nupkg
%NUGET% push ServiceStack.Plugins.ProtoBuf.3.9.60.symbols.nupkg
%NUGET% push ServiceStack.Razor.3.9.60.nupkg
%NUGET% push ServiceStack.Razor.3.9.60.symbols.nupkg
