import JsonBlock from './JsonBlock.mjs'
import RecordedAnswers from './RecordedAnswers.mjs'
import StudioNotice from './StudioNotice.mjs'
import { expectation, label } from './recipeModel.mjs'
export default {
    components: { JsonBlock, StudioNotice, RecordedAnswers },
    props: {
        recipe: Object,
        results: Object,
        checking: Boolean,
        canRun: Boolean,
        canSaveExample: Boolean,
    },
    emits: ['load', 'add', 'remove', 'check', 'stop', 'rename'],
    setup(_, { emit }) {
        return {
            rename: (event, example) => {
                const label = event.target.value.trim()
                event.target.value = label || example.label
                if (label && label !== example.label) emit('rename', { id: example.id, label })
            },
            expectation,
            label,
            changed: (run, recipe) =>
                JSON.stringify(run.recipe.questions) !==
                JSON.stringify(recipe.questions),
        }
    },
    template: `<section data-jev-examples><div data-jev-section-heading class="flex items-center justify-between gap-3 flex-wrap mb-4.5 max-[620px]:gap-2.5"><div><h3 class="text-base font-semibold">Try it on examples</h3><p data-jev-help class="text-xs text-slate-500 dark:text-slate-400 leading-[1.6] mt-1">Run the recipe, then save a successful run to keep its actual input and results.</p></div><div data-jev-actions class="flex items-center gap-2.5 flex-wrap"><button type="button" :disabled="!canSaveExample" @click="$emit('add')" data-jev-button class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3 inline-flex items-center justify-center gap-1.75 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-200 text-xs font-medium py-2 px-3 whitespace-normal text-center leading-[1.5] no-underline hover:bg-slate-100 hover:dark:bg-slate-800 pointer-coarse:min-h-11">Save last run as example</button><button v-if="!checking"  type="button" :disabled="!canRun||!recipe.examples?.length" @click="$emit('check')" data-jev-button data-jev-primary class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3 inline-flex items-center justify-center gap-1.75 border border-gray-200 dark:border-gray-700 rounded-lg bg-indigo-600 text-white text-xs font-medium py-2 px-3 whitespace-normal text-center leading-[1.5] no-underline hover:bg-indigo-700 border-indigo-600 pointer-coarse:min-h-11">Check {{recipe.examples?.length||0}} examples</button><button v-else type="button" @click="$emit('stop')" data-jev-button class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3 inline-flex items-center justify-center gap-1.75 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-200 text-xs font-medium py-2 px-3 whitespace-normal text-center leading-[1.5] no-underline hover:bg-slate-100 hover:dark:bg-slate-800 pointer-coarse:min-h-11">Stop checks</button></div></div>
      <StudioNotice v-if="checking" message="Checking examples sequentially. Each case is a separate Jev call."/>
      <p v-if="!recipe.examples?.length"  data-jev-empty-inline class="py-[35px] px-5 bg-slate-50 dark:bg-gray-800 rounded-[10px] text-slate-500 dark:text-slate-400 text-[13px]">Run the recipe, then choose Save as example to keep its actual input and results.</p>
      <article v-for="example in recipe.examples" :key="example.id"  data-jev-example class="mt-5 p-5 border border-gray-200 dark:border-gray-700 rounded-[10px] max-[620px]:p-[15px]"><div data-jev-section-heading class="flex items-center justify-between gap-3 flex-wrap mb-2 max-[620px]:gap-2.5"><input :value="example.label" :aria-label="'Name for '+example.label" maxlength="120" @change="rename($event,example)" class="min-w-0 flex-1 w-full border border-transparent rounded-md bg-transparent text-sm font-semibold px-2 py-1 hover:border-gray-200 dark:hover:border-gray-700 focus-visible:outline-2 focus-visible:outline-indigo-600"/><div data-jev-actions class="flex items-center gap-2.5 flex-wrap"><button type="button" @click="$emit('load',example)" data-jev-button class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3 inline-flex items-center justify-center gap-1.75 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-200 text-xs font-medium py-2 px-3 whitespace-normal text-center leading-[1.5] no-underline hover:bg-slate-100 hover:dark:bg-slate-800 pointer-coarse:min-h-11">Use input</button><button type="button" :aria-label="'Remove example '+example.label" @click="$emit('remove',example.id)" data-jev-icon-button class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3 bg-transparent text-slate-500 dark:text-slate-400 border-0 rounded-md p-1.75 inline-flex items-center justify-center hover:bg-slate-100 hover:dark:bg-slate-800 hover:text-gray-800 hover:dark:text-gray-200 max-[620px]:min-w-8 max-[620px]:min-h-8 pointer-coarse:min-h-11">×</button></div></div>
        <details data-jev-criteria class="text-xs text-slate-500 dark:text-slate-400 mt-4"><summary class="cursor-pointer focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3">Input</summary><JsonBlock :text="JSON.stringify(example.input,null,2)"/></details>
        <section v-if="example.execution" data-jev-recorded-example class="mt-4"><h5 class="text-sm font-semibold">Recorded result</h5><p class="text-xs text-slate-500 dark:text-slate-400 mt-1">{{example.execution.model}} · {{new Date(example.execution.completedAt).toLocaleString()}}</p><RecordedAnswers :recipe="recipe" :execution="example.execution"/></section>
        <p data-jev-help class="my-3 mx-0 text-xs text-slate-500 dark:text-slate-400 leading-[1.6]">{{example.provenance==='user-reviewed'?'Expectations reviewed by you':example.provenance==='ai-suggested'?'AI-suggested expectations':example.execution?'Actual output from a successful run':'Illustrative example'}}{{example.notes?' · '+example.notes:''}}</p>
        <div v-if="Object.keys(example.expected||{}).length"  data-jev-help class="text-xs text-slate-500 dark:text-slate-400 leading-[1.6] my-3 mx-0">Expected: <span v-for="(value,key) in example.expected" :key="key">{{label(key)}} = {{value}} · </span></div>
        <div v-if="results?.[example.id]"  aria-live="polite" data-jev-example-results class="border-t border-t-gray-200 dark:border-t-gray-700 pt-3 mt-[15px]"><StudioNotice v-if="results[example.id].error" tone="error" :message="results[example.id].error"/><StudioNotice v-if="changed(results[example.id],recipe)" tone="warning" message="These results use an earlier question definition. Check again after your edits."/><div v-for="(answer,key) in results[example.id].answers" :key="key"  data-jev-row class="flex items-center gap-2.5 flex-wrap justify-between text-xs mt-2"><span>{{results[example.id].recipe.presentation?.questions?.[key]?.label||label(key)}}: {{answer.choice??answer.score??answer.noul}}</span><span data-jev-help class="text-xs text-slate-500 dark:text-slate-400 leading-[1.6] my-3 mx-0">{{changed(results[example.id],recipe)?'Earlier recipe':expectation(example,key,answer)}}</span></div></div>
      </article><p data-jev-help class="text-xs text-slate-500 dark:text-slate-400 leading-[1.6]">Checks compare new results with the saved run. Score comparisons match within half a level; yes/no comparisons use 0.5 for inspection only. Older examples may also show their original expected answers.</p>
    </section>`,
}
