import { cost } from './recipeModel.mjs'
export default {
    props: { items: Array, cursor: String, loading: Boolean },
    emits: ['select', 'more', 'refresh', 'clear'],
    setup() {
        return { cost, date: (value) => new Date(value * 1000).toLocaleString() }
    },
    template: `<section><div data-jev-section-heading class="flex items-center justify-between gap-3 flex-wrap mb-4.5 max-[620px]:gap-2.5"><div><h3 class="text-base font-semibold">Your decision history</h3><p data-jev-help class="text-xs text-slate-500 dark:text-slate-400 leading-[1.6] mt-1">Each call keeps the exact recipe and input it evaluated.</p></div><div data-jev-actions class="flex items-center gap-2.5 flex-wrap"><button type="button" @click="$emit('refresh')" :disabled="loading" data-jev-button class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3 inline-flex items-center justify-center gap-1.75 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-200 text-xs font-medium py-2 px-3 whitespace-normal text-center leading-[1.5] no-underline hover:bg-slate-100 hover:dark:bg-slate-800 pointer-coarse:min-h-11">Refresh</button><button v-if="items.length"  type="button" @click="$emit('clear')" data-jev-button class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3 inline-flex items-center justify-center gap-1.75 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-200 text-xs font-medium py-2 px-3 whitespace-normal text-center leading-[1.5] no-underline hover:bg-slate-100 hover:dark:bg-slate-800 pointer-coarse:min-h-11">Clear history</button></div></div>
      <p v-if="loading"  role="status" data-jev-help class="text-xs text-slate-500 dark:text-slate-400 leading-[1.6]">Loading decisions…</p><div v-if="!items.length&&!loading"  data-jev-empty-inline class="py-[35px] px-5 bg-slate-50 dark:bg-gray-800 rounded-[10px] text-slate-500 dark:text-slate-400 text-[13px]">Your completed and interrupted decisions will appear here.</div>
      <button v-for="run in items" :key="run.id" type="button"  @click="$emit('select',run.id)" data-jev-history-row class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3 flex items-center justify-between gap-5 w-full py-4.5 px-3 bg-transparent border-0 border-b border-b-gray-200 dark:border-b-gray-700 text-gray-800 dark:text-gray-200 text-left rounded-md hover:bg-slate-50 hover:dark:bg-gray-800"><span class="flex flex-col gap-1 min-w-0"><strong class="text-[13px] font-medium">{{run.name}}</strong><span data-jev-help class="text-xs text-slate-500 dark:text-slate-400 leading-[1.6]">{{date(run.createdAt)}}</span></span><span data-jev-history-summary class="flex items-center gap-3.5 text-xs max-[620px]:flex-col max-[620px]:items-end max-[620px]:gap-1.25"><span data-jev-badge class="inline-flex bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 text-[11px] rounded-[5px] py-0.75 px-[7px] items-center font-normal">{{run.status}}</span><span>{{cost(run.usage?.cost)}}</span></span></button>
      <button v-if="cursor" type="button"  @click="$emit('more')" :disabled="loading" data-jev-button data-jev-more class="cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-indigo-600 focus-visible:dark:outline-indigo-300 focus-visible:outline-offset-3 inline-flex items-center justify-center gap-1.75 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-200 text-xs font-medium py-2 px-3 whitespace-normal text-center leading-[1.5] no-underline hover:bg-slate-100 hover:dark:bg-slate-800 mt-5 pointer-coarse:min-h-11">Load more</button>
    </section>`,
}
