using System.Text;
using System.Text.Json.Nodes;
using Microsoft.Extensions.Logging;
using ServiceStack.Text;

namespace ServiceStack.AI;

/// <summary>
/// Base for non-text modality providers — image/audio/speech/transcription generators
/// (port of llms-py's GeneratorBase, main.py:1094).
///
/// A generator is attached to a parent provider's <see cref="ChatProvider.Modalities"/> and is invoked
/// by <see cref="OpenAiCompatibleProvider.ChatAsync"/> when a chat requests that modality. Generated
/// media is written to the content-addressed cache (which fires the cache_saved filters, so the gallery
/// picks it up automatically) and returned in the OpenAI response shape the UI already renders.
/// </summary>
/// <remarks>
/// Extends OpenAiCompatibleProvider (rather than ChatProvider like Python's GeneratorBase) purely to
/// inherit ProcessChatAsync/CreateHttpClient/ReadJsonResponseAsync; ChatAsync is always overridden.
/// </remarks>
public abstract class GeneratorProvider : OpenAiCompatibleProvider
{
    public virtual string DefaultContent => "I've generated the image for you.";

    /// <summary>Per-generator aspect ratio → "WxH" overrides; falls back to ChatFeature.AspectRatios</summary>
    public Dictionary<string, string> AspectRatios { get; set; } = [];

    public override void Populate(JsonObject kwargs)
    {
        // A generator declared under a provider's llms.json "modalities" only carries {name, npm}
        // — it posts to its own endpoint using the parent's key, so unlike a top-level provider
        // it doesn't require id/api (Python's GeneratorBase reads them with .get()).
        kwargs["id"] ??= Sdk;
        kwargs["api"] ??= "";
        base.Populate(kwargs);
    }

    /// <summary>Generators don't do tool calling — strip tools before normalizing (Python parity)</summary>
    public async Task<JsonObject> ProcessGeneratorChatAsync(JsonObject chat, ChatProvider? parent)
    {
        var clone = chat.Clone();
        clone.Remove("tools");
        clone.Remove("tool_choice");
        clone.Remove("parallel_tool_calls");
        return await ProcessChatAsync(clone, parent?.Id ?? Id).ConfigAwait();
    }

    /// <summary>Auth header from this generator's key, or the parent provider's when nested</summary>
    protected Dictionary<string, string> GetHeaders(ChatProvider? parent = null)
    {
        var headers = new Dictionary<string, string>(Headers)
        {
            ["Accept"] = MimeTypes.Json,
        };
        var apiKey = parent?.ApiKey ?? ApiKey;
        if (!string.IsNullOrEmpty(apiKey))
            headers["Authorization"] = $"Bearer {apiKey}";
        return headers;
    }

    protected async Task<JsonObject> PostJsonAsync(string url, JsonObject body,
        Dictionary<string, string> headers, ChatContext context)
    {
        using var client = CreateHttpClient();
        var httpReq = new HttpRequestMessage(HttpMethod.Post, url);
        foreach (var entry in headers)
        {
            if (!entry.Key.EqualsIgnoreCase("Content-Type"))
                httpReq.Headers.TryAddWithoutValidation(entry.Key, entry.Value);
        }
        httpReq.Content = new StringContent(body.ToJsonString(ChatJson.Options), Encoding.UTF8, MimeTypes.Json);

        Log.LogInformation("POST {Url}", url);
        using var res = await client.SendAsync(httpReq, context.CancellationToken).ConfigAwait();
        var response = await OpenAiCompatibleProvider.ReadJsonResponseAsync(res).ConfigAwait();
        context.ProviderResponse = response;
        return response;
    }

    /// <summary>Resolve the requested aspect ratio to a "WxH" size string</summary>
    protected (string Size, int Width, int Height) ResolveSize(JsonObject chat, string defaultRatio = "1:1")
    {
        var ratio = ChatMessages.ChatToAspectRatio(chat) ?? defaultRatio;
        var size = AspectRatios.GetValueOrDefault(ratio)
            ?? ChatFeature.AspectRatios.GetValueOrDefault(ratio)
            ?? ChatFeature.AspectRatios[defaultRatio];
        size = size.Replace("×", "x");
        var parts = size.Split('x');
        return (size, int.Parse(parts[0]), int.Parse(parts[1]));
    }

    /// <summary>
    /// Cache generated bytes and return the /~cache/ url. Goes through ChatFeature.SaveToCache so the
    /// .info.json sidecar is written and the gallery's cache_saved filter records the media.
    /// </summary>
    protected string CacheMedia(byte[] bytes, string filename, string mimeType, ChatContext context,
        JsonObject? info = null)
    {
        var extraInfo = info?.Clone() ?? new JsonObject();
        var saved = Feature!.SaveToCache(bytes, filename, mimeType, context.User, extraInfo);
        return saved.GetString("url")!;
    }

    /// <summary>Download a generated asset the provider returned as a URL</summary>
    protected async Task<(byte[] Bytes, string MimeType, string FileName)> DownloadAsync(
        string url, string defaultFileName, CancellationToken token)
    {
        using var client = CreateHttpClient();
        using var res = await client.GetAsync(url, token).ConfigAwait();
        res.EnsureSuccessStatusCode();
        var bytes = await res.Content.ReadAsByteArrayAsync(token).ConfigAwait();
        var mimeType = res.Content.Headers.ContentType?.MediaType ?? "image/png";
        var fileName = res.Content.Headers.ContentDisposition?.FileName?.Trim('"') ?? defaultFileName;
        return (bytes, mimeType, fileName);
    }

    /// <summary>
    /// The OpenAI-shaped response the orchestrator and UI expect, with generated media attached as
    /// grouped resource parts (images/audios) on the assistant message.
    /// </summary>
    protected JsonObject BuildMediaResponse(string group, JsonArray media, JsonObject? usage = null,
        double? cost = null, string? content = null)
    {
        var message = new JsonObject
        {
            ["role"] = "assistant",
            ["content"] = content ?? DefaultContent,
            [group] = media,
        };
        var ret = new JsonObject
        {
            ["choices"] = new JsonArray(new JsonObject { ["index"] = 0, ["message"] = message, ["finish_reason"] = "stop" }),
            ["created"] = DateTimeOffset.UtcNow.ToUnixTimeSeconds(),
            ["model"] = Id,
            ["usage"] = usage?.Clone() ?? new JsonObject
            {
                ["prompt_tokens"] = 0,
                // per-image pricing is modelled as 1M completion tokens (Python parity)
                ["completion_tokens"] = 1_000_000,
            },
        };
        if (cost != null)
            ret["cost"] = cost;
        return ret;
    }

    protected static JsonObject ImagePart(string url) => new()
    {
        ["type"] = "image_url",
        ["image_url"] = new JsonObject { ["url"] = url },
    };

    protected static JsonObject AudioPart(string url) => new()
    {
        ["type"] = "audio_url",
        ["audio_url"] = new JsonObject { ["url"] = url },
    };
}
